[package]
name = "planner-rs"
version = "0.1.0"
edition = "2021"

[[package.graphs]]
path = "src/graphs"

[[package.algorithms]]
path = "src/graphs/algorithms"

[dependencies]
derive-new = "0.5.9"
lazy_static = "1.4.0"
strum = { version = "0.24.1", features = ["derive"] }
