use strum::EnumIter;

#[derive(EnumIter, PartialEq, Eq, Clone, Copy, Debug, Hash)]
pub enum Subject {
    PolishALiteratureHL,
    PolishALiteratureSL,
    EnglishALanguageAndLiteratureHL,
    EnglishALanguageAndLiteratureSL,
    EnglishBHL,
    GermanBHL,
    GermanBSL,
    GermanAbInitioSL,
    FrenchBHL,
    FrenchBSL,
    FrenchAbInitioSL,
    SpanishAbInitioSL,
    SpanishBHL,
    SpanishBSL,
    EconomicsHL,
    EconomicsSL,
    GeographyHL,
    GeographySL,
    HistoryHL,
    HistorySL,
    BiologyHL,
    BiologySL,
    ChemistryHL,
    ChemistrySL,
    PhysicsHL,
    PhysicsSL,
    ComputerScienceHL,
    ComputerScienceSL,
    MathematicsAAHL,
    MathematicsAASL,
    MathematicsAISL,
    TOK,
}
